version: '3.7'

# test
networks:
  microservices:
    driver: bridge
## common.yml equals this networks

services:
  config-service:
    image: com.jar.service.system/config.service:1.0-DEPLOY
    ports:
      - "8888:8888"
    networks:
      - microservices
      
  discovery-service:
    image: com.jar.service.system/discovery.service:1.0-DEPLOY
    ports:
      - "8761:8761"
    depends_on:
      - config-service
    networks:
      - microservices

  gateway-service:
    image: com.jar.service.system/gateway.service:1.0-DEPLOY
    ports:
      - "8600:8600"
    depends_on:
      - config-service
      - discovery-service
    networks:
      - microservices

  user-service:
    image: com.jar.service.system/user.service:1.0-DEPLOY
    ports:
      - "8100:8100"
    depends_on:
      - config-service
      - discovery-service
    networks:
      - microservices
  
  database-service:
    image: com.jar.service.system/database.service:1.0-DEPLOY
    ports:
      - "8200:8200"
    depends_on:
      - config-service
      - discovery-service
    networks:
      - microservices

  apporder-service:
    image: com.jar.service.system/apporder.service:1.0-DEPLOY
    ports:
      - "8300:8300"
    depends_on:
      - config-service
      - discovery-service
    networks:
      - microservices

  storage-service:
  image: com.jar.service.system/storage.service:1.0-DEPLOY
  ports:
    - "8400:8400"
  depends_on:
    - config-service
    - discovery-service
  networks:
    - microservices

  container-service:
  image: com.jar.service.system/container.service:1.0-DEPLOY
  ports:
    - "8500:8500"
  depends_on:
    - config-service
    - discovery-service
  networks:
    - microservices